--------------------------------------------------------
--  File created - Saturday-November-17-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table JAGA1_COSTUMERMASTER
--------------------------------------------------------

  CREATE TABLE "HR"."JAGA1_COSTUMERMASTER" 
   (	"CUSTOMERID" NUMBER(10,0), 
	"CUSTOMERCODE" VARCHAR2(30 BYTE), 
	"COSTUMERNAME" VARCHAR2(30 BYTE), 
	"CUSTOMERADDRESS1" VARCHAR2(100 BYTE), 
	"COSTOMERADDRESS2" VARCHAR2(100 BYTE), 
	"CUSTOMERPINCODE" NUMBER(6,0), 
	"EMAILADDRESS" VARCHAR2(100 BYTE), 
	"CONTACTNUMBER" NUMBER(20,0), 
	"PRIMARYCONTACTPERSON" VARCHAR2(100 BYTE), 
	"RECORDSTATUS" VARCHAR2(1 BYTE), 
	"ACTIVEINACTIVFLAG" VARCHAR2(1 BYTE), 
	"CREATEDATE" DATE, 
	"CREATEDBY" VARCHAR2(30 BYTE), 
	"MODIFIEDDATE" DATE, 
	"MODIFIEDBY" VARCHAR2(30 BYTE), 
	"AUTHORIZEDDATE" DATE, 
	"AUTHORIZEDBY" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.JAGA1_COSTUMERMASTER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007002
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007002" ON "HR"."JAGA1_COSTUMERMASTER" ("CUSTOMERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table JAGA1_COSTUMERMASTER
--------------------------------------------------------

  ALTER TABLE "HR"."JAGA1_COSTUMERMASTER" ADD PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."JAGA1_COSTUMERMASTER" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
